# -*- coding: utf-8 -*-
"""Amanda_UTS BIG DATA_14022300055_6C SI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyP-LSle6gXOvsFwOzTFihEzJ_lDvbtw
"""

pip install google-play-scraper

from google_play_scraper import reviews, Sort
import pandas as pd
from transformers import pipeline

# 1. PROSES SCRAPING (Mengambil ulasan SERBA DIGI)
print("Sedang mengambil ulasan dari SERBA DIGI...")
result, _ = reviews(
    'id.citigov.serangkab', # ID aplikasi SERBA DIGI
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=100, # Jumlah ulasan yang diambil
    filter_score_with=None
)

# 2. PROSES TRANSFORMER (Load AI IndoRoBERTa)
print("Memuat model AI IndoRoBERTa untuk membaca data...")
# Menggunakan model IndoRoBERTa khusus sentimen bahasa Indonesia
model_name = "w11wo/indonesian-roberta-base-sentiment-classifier"
nlp_ai = pipeline("sentiment-analysis", model=model_name)

# 3. ANALISIS DATA
data_final = []
for review in result:
    teks = review['content']
    # AI menganalisis teks ulasan (max 512 karakter)
    hasil_ai = nlp_ai(teks[:512])[0]

    data_final.append({
        'userName': review['userName'],
        'score': review['score'],
        'at': review['at'],
        'content': teks,
        'Analisis_AI': hasil_ai['label'],
        'Skor_Kepastian': round(hasil_ai['score'], 4)
    })

# 4. SIMPAN DAN TAMPILKAN
df = pd.DataFrame(data_final)
df.to_csv('hasil_uts_bmkg_ai.csv', index=False)
print("Selesai! File 'hasil_uts_bmkg_ai.csv' telah dibuat.")
df.head() # Menampilkan pratinjau hasil